-- 002_full_schema.down.sql — Full PostgreSQL schema rollback
--
-- Drops all 24 tables in reverse FK dependency order (children before parents).
-- Drops indexes before tables.

-- Drop indexes (all tables)
DROP INDEX IF EXISTS idx_backup_approvers_user_id;
DROP INDEX IF EXISTS idx_backup_approvers_org_id;
DROP INDEX IF EXISTS idx_budget_caps_project_id;
DROP INDEX IF EXISTS idx_budget_caps_user_id;
DROP INDEX IF EXISTS idx_budget_caps_org_id;
DROP INDEX IF EXISTS idx_financial_cutoff_periods_dates;
DROP INDEX IF EXISTS idx_financial_cutoff_periods_project_id;
DROP INDEX IF EXISTS idx_financial_cutoff_periods_org_id;
DROP INDEX IF EXISTS idx_refresh_tokens_user_id;
DROP INDEX IF EXISTS idx_refresh_tokens_token_hash;
DROP INDEX IF EXISTS idx_password_resets_user_id;
DROP INDEX IF EXISTS idx_invitations_organization_id;
DROP INDEX IF EXISTS idx_expense_approvals_user_id;
DROP INDEX IF EXISTS idx_expense_approvals_expense_id;
DROP INDEX IF EXISTS idx_expenses_user_date;
DROP INDEX IF EXISTS idx_expenses_expense_date;
DROP INDEX IF EXISTS idx_expenses_status;
DROP INDEX IF EXISTS idx_expenses_unit_id;
DROP INDEX IF EXISTS idx_expenses_project_id;
DROP INDEX IF EXISTS idx_expenses_user_id;
DROP INDEX IF EXISTS idx_expenses_org_id;
DROP INDEX IF EXISTS idx_time_entry_approvals_user_id;
DROP INDEX IF EXISTS idx_time_entry_approvals_time_entry_id;
DROP INDEX IF EXISTS idx_time_entries_is_deleted;
DROP INDEX IF EXISTS idx_time_entries_user_date;
DROP INDEX IF EXISTS idx_time_entries_entry_date;
DROP INDEX IF EXISTS idx_time_entries_status;
DROP INDEX IF EXISTS idx_time_entries_unit_id;
DROP INDEX IF EXISTS idx_time_entries_wg_id;
DROP INDEX IF EXISTS idx_time_entries_project_id;
DROP INDEX IF EXISTS idx_time_entries_user_id;
DROP INDEX IF EXISTS idx_time_entries_org_id;
DROP INDEX IF EXISTS idx_wg_members_unit_id;
DROP INDEX IF EXISTS idx_wg_members_user_id;
DROP INDEX IF EXISTS idx_wg_members_wg_id;
DROP INDEX IF EXISTS idx_working_groups_manager_id;
DROP INDEX IF EXISTS idx_working_groups_subproject_id;
DROP INDEX IF EXISTS idx_working_groups_org_id;
DROP INDEX IF EXISTS idx_subprojects_project_id;
DROP INDEX IF EXISTS idx_project_managers_user_id;
DROP INDEX IF EXISTS idx_project_managers_project_id;
DROP INDEX IF EXISTS idx_project_adoptions_organization_id;
DROP INDEX IF EXISTS idx_project_adoptions_project_id;
DROP INDEX IF EXISTS idx_projects_customer_id;
DROP INDEX IF EXISTS idx_projects_org_id;
DROP INDEX IF EXISTS idx_contract_adoptions_organization_id;
DROP INDEX IF EXISTS idx_contract_adoptions_contract_id;
DROP INDEX IF EXISTS idx_contracts_created_by_org_id;
DROP INDEX IF EXISTS idx_contracts_customer_id;
DROP INDEX IF EXISTS idx_unit_memberships_user_primary;
DROP INDEX IF EXISTS idx_unit_memberships_user_org;
DROP INDEX IF EXISTS idx_unit_memberships_unit_id;
DROP INDEX IF EXISTS idx_unit_memberships_user_id;
DROP INDEX IF EXISTS idx_unit_memberships_org_id;
DROP INDEX IF EXISTS idx_organization_memberships_organization_id;
DROP INDEX IF EXISTS idx_organization_memberships_user_id;
DROP INDEX IF EXISTS idx_units_org_code;
DROP INDEX IF EXISTS idx_units_parent_unit_id;
DROP INDEX IF EXISTS idx_units_org_id;
DROP INDEX IF EXISTS idx_customers_org_id;
DROP INDEX IF EXISTS idx_users_username;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_organizations_slug;

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS backup_approvers;
DROP TABLE IF EXISTS budget_caps;
DROP TABLE IF EXISTS financial_cutoff_periods;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS expense_approvals;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS time_entry_approvals;
DROP TABLE IF EXISTS time_entries;
DROP TABLE IF EXISTS wg_members;
DROP TABLE IF EXISTS working_groups;
DROP TABLE IF EXISTS subprojects;
DROP TABLE IF EXISTS project_managers;
DROP TABLE IF EXISTS project_adoptions;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS contract_adoptions;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS unit_memberships;
DROP TABLE IF EXISTS organization_memberships;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;

DROP EXTENSION IF EXISTS pgcrypto;
