/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTimeEntriesIndexRouteImport } from './routes/_authenticated/time-entries/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedOrgHierarchyIndexRouteImport } from './routes/_authenticated/org-hierarchy/index'
import { Route as AuthenticatedExportsIndexRouteImport } from './routes/_authenticated/exports/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthPasswordResetIndexRouteImport } from './routes/_auth/password-reset/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthInviteIndexRouteImport } from './routes/_auth/invite/index'
import { Route as AuthBootstrapIndexRouteImport } from './routes/_auth/bootstrap/index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedContractsIdIndexRouteImport } from './routes/_authenticated/contracts/$id/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimeEntriesIndexRoute =
  AuthenticatedTimeEntriesIndexRouteImport.update({
    id: '/time-entries/',
    path: '/time-entries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgHierarchyIndexRoute =
  AuthenticatedOrgHierarchyIndexRouteImport.update({
    id: '/org-hierarchy/',
    path: '/org-hierarchy/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportsIndexRoute =
  AuthenticatedExportsIndexRouteImport.update({
    id: '/exports/',
    path: '/exports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordResetIndexRoute = AuthPasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteIndexRoute = AuthInviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBootstrapIndexRoute = AuthBootstrapIndexRouteImport.update({
  id: '/bootstrap/',
  path: '/bootstrap/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsIdIndexRoute =
  AuthenticatedContractsIdIndexRouteImport.update({
    id: '/contracts/$id/',
    path: '/contracts/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/bootstrap/': typeof AuthBootstrapIndexRoute
  '/invite/': typeof AuthInviteIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/password-reset/': typeof AuthPasswordResetIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/exports/': typeof AuthenticatedExportsIndexRoute
  '/org-hierarchy/': typeof AuthenticatedOrgHierarchyIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/time-entries/': typeof AuthenticatedTimeEntriesIndexRoute
  '/contracts/$id/': typeof AuthenticatedContractsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/bootstrap': typeof AuthBootstrapIndexRoute
  '/invite': typeof AuthInviteIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/password-reset': typeof AuthPasswordResetIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/exports': typeof AuthenticatedExportsIndexRoute
  '/org-hierarchy': typeof AuthenticatedOrgHierarchyIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/time-entries': typeof AuthenticatedTimeEntriesIndexRoute
  '/contracts/$id': typeof AuthenticatedContractsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_auth/bootstrap/': typeof AuthBootstrapIndexRoute
  '/_auth/invite/': typeof AuthInviteIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/password-reset/': typeof AuthPasswordResetIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/exports/': typeof AuthenticatedExportsIndexRoute
  '/_authenticated/org-hierarchy/': typeof AuthenticatedOrgHierarchyIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/time-entries/': typeof AuthenticatedTimeEntriesIndexRoute
  '/_authenticated/contracts/$id/': typeof AuthenticatedContractsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/$id'
    | '/projects/$id'
    | '/bootstrap/'
    | '/invite/'
    | '/login/'
    | '/password-reset/'
    | '/register/'
    | '/contracts/'
    | '/expenses/'
    | '/exports/'
    | '/org-hierarchy/'
    | '/projects/'
    | '/time-entries/'
    | '/contracts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$id'
    | '/projects/$id'
    | '/bootstrap'
    | '/invite'
    | '/login'
    | '/password-reset'
    | '/register'
    | '/contracts'
    | '/expenses'
    | '/exports'
    | '/org-hierarchy'
    | '/projects'
    | '/time-entries'
    | '/contracts/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/projects/$id'
    | '/_auth/bootstrap/'
    | '/_auth/invite/'
    | '/_auth/login/'
    | '/_auth/password-reset/'
    | '/_auth/register/'
    | '/_authenticated/contracts/'
    | '/_authenticated/expenses/'
    | '/_authenticated/exports/'
    | '/_authenticated/org-hierarchy/'
    | '/_authenticated/projects/'
    | '/_authenticated/time-entries/'
    | '/_authenticated/contracts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/time-entries/': {
      id: '/_authenticated/time-entries/'
      path: '/time-entries'
      fullPath: '/time-entries/'
      preLoaderRoute: typeof AuthenticatedTimeEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org-hierarchy/': {
      id: '/_authenticated/org-hierarchy/'
      path: '/org-hierarchy'
      fullPath: '/org-hierarchy/'
      preLoaderRoute: typeof AuthenticatedOrgHierarchyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports/': {
      id: '/_authenticated/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof AuthenticatedExportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/password-reset/': {
      id: '/_auth/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof AuthPasswordResetIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invite/': {
      id: '/_auth/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof AuthInviteIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bootstrap/': {
      id: '/_auth/bootstrap/'
      path: '/bootstrap'
      fullPath: '/bootstrap/'
      preLoaderRoute: typeof AuthBootstrapIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/$id/': {
      id: '/_authenticated/contracts/$id/'
      path: '/contracts/$id'
      fullPath: '/contracts/$id/'
      preLoaderRoute: typeof AuthenticatedContractsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBootstrapIndexRoute: typeof AuthBootstrapIndexRoute
  AuthInviteIndexRoute: typeof AuthInviteIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthPasswordResetIndexRoute: typeof AuthPasswordResetIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBootstrapIndexRoute: AuthBootstrapIndexRoute,
  AuthInviteIndexRoute: AuthInviteIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthPasswordResetIndexRoute: AuthPasswordResetIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedExportsIndexRoute: typeof AuthenticatedExportsIndexRoute
  AuthenticatedOrgHierarchyIndexRoute: typeof AuthenticatedOrgHierarchyIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTimeEntriesIndexRoute: typeof AuthenticatedTimeEntriesIndexRoute
  AuthenticatedContractsIdIndexRoute: typeof AuthenticatedContractsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedExportsIndexRoute: AuthenticatedExportsIndexRoute,
  AuthenticatedOrgHierarchyIndexRoute: AuthenticatedOrgHierarchyIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTimeEntriesIndexRoute: AuthenticatedTimeEntriesIndexRoute,
  AuthenticatedContractsIdIndexRoute: AuthenticatedContractsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
